name: machine_hour_rate
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  loading_animation_widget: ^1.3.0
  cupertino_icons: ^1.0.2
  # country_picker: ^2.0.23
  package_info_plus: ^4.2.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.3
  shared_preferences: ^2.2.3
  pdf: ^3.10.7
  permission_handler: ^11.0.1
  path_provider: ^2.1.2
  pie_chart: ^5.4.0
  dropdown_button2: ^2.3.9
  http: ^1.1.0
  fluttertoast: ^8.2.2
  pin_code_fields: ^8.0.1
  # intl_phone_field: ^3.2.0
  connectivity_plus: ^5.0.2
  # animated_bottom_navigation_bar: ^1.3.3
  win32: ^5.10.1
  file_picker: ^6.1.1
  image_picker: ^1.1.0
  # ulid: ^2.0.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons : ^0.14.3

flutter_icons:
  image_path: "assets/icon/app.png" 
  android: true
  ios: true
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/icon/
  - assets/logo.png
  - assets/Animation - tick.gif

  # fonts:
  #   - family: DejaVuSans
  #     fonts:
  #       - asset: assets/fonts/DejaVuSans.ttf