name: machine_hour_rate
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.0
  # go_router: ^11.1.4
  skeletonizer: ^1.4.3
  loading_animation_widget: ^1.3.0
  cupertino_icons: ^1.0.2
  country_picker: ^2.0.23
  pin_code_fields: ^8.0.1
  package_info_plus: ^4.2.0
  share_plus: ^7.2.2
  url_launcher: ^6.2.3
  shared_preferences: ^2.2.3
  pdf: ^3.11.2
  permission_handler: ^11.0.1
  path_provider: ^2.1.3
  pie_chart: ^5.4.0
  dropdown_button2: ^2.3.9
  http: ^1.1.0
  # intl_phone_field: ^3.2.0
  fluttertoast: ^8.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
  - assets/
  - assets/logo.png